version: 2

sources: 
  - name: football_db
    schema: public 
    tables: 
      - name: matches
        description: "Information for each match from 2000 to 2019"

      - name: EPLStandings
        description: "Standing of each team at the end of the season from 2000 to 2015"
