football_prediction:
  outputs:
    dev:
      dbname: football_db
      host: localhost
      password: meomeomeo123
      port: 5433
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
